#
#
#
#| vscode: {languageId: r}
library(dplyr)
library(tibble)
library(tidyr)
library(ggplot2)
library(forcats)
library(readxl)
library(lubridate)
library(patchwork)
library(stringr)
library(plotly)
library(reshape2)
library(sf)
library(jsonlite)
#
#
#
#| vscode: {languageId: r}
layoff_data <- read.csv("./data/Clean/layoff_cleaned_2.csv")
layoff_data <- layoff_data |> rename(Date = `Received.Date`)
unemployment_data <- read_excel("./data/Raw/Unemployment/UNRATE.xls", skip = 10)
unemployment_data <- unemployment_data |> rename(Date = observation_date)
# head(layoff_data, 5)
#
#
#
#| vscode: {languageId: r}
layoff_data$Date <- as.POSIXct(layoff_data$Date, format = "%Y-%m-%d")
layoff_data$effective_date_cleaned <- as.POSIXct(layoff_data$effective_date_cleaned, format = "%Y-%m-%d")
#
#
#
#| vscode: {languageId: r}
head(layoff_data)
#
#
#
#| vscode: {languageId: r}
dji_stock_indices_data <- read.csv("./data/Raw/Stock_Indices/DowJonesIndex.csv")
snp_stock_indices_data <- read.csv("./data/Raw/Stock_Indices/S&P500.csv")
nasdaq_stock_indices_data <- read.csv("./data/Raw/Stock_Indices/NASDAQ.csv")

dji_stock_indices_data$Date <- as.POSIXct(dji_stock_indices_data$Date, format = "%m/%d/%y")
snp_stock_indices_data$Date <- as.POSIXct(snp_stock_indices_data$Date, format = "%m/%d/%y")
nasdaq_stock_indices_data$Date <- as.POSIXct(nasdaq_stock_indices_data$Date, format = "%Y-%m-%d")
#
#
#
# Time series plot for layoff numbers

layoff_data_2015 <- layoff_data %>%
    filter(Date > as.Date("2015-01-01"))

# Extract month and year from Date
agg_layoffs <- layoff_data_2015 %>%
    group_by(month = format(Date, "%Y-%m")) %>%
    summarize(total_laid_off = sum(`Number.of.Workers`))

agg_layoffs$month <- as.Date(paste0(agg_layoffs$month, "-01"), format = "%Y-%m-%d")

ggplot(agg_layoffs, aes(x = month, y = total_laid_off)) +
    geom_line() +
    geom_point() +
    labs(
        title = "Number.of.Workers Laid Off Each Month",
        x = "Month",
        y = "Total Laid Off"
    ) +
    theme_minimal()



plot_ly(layoff_data, x = ~Date, y = ~`Number.of.Workers`, type = "scatter", mode = "lines") %>%
    layout(
        title = "Time Series Plot for Number of Layoffs",
        xaxis = list(title = "Data Laid Off"),
        yaxis = list(title = "Number.of.Workers")
    )
#
#
#
#
url <- "https://www2.census.gov/geo/tiger/GENZ2022/shp/cb_2022_us_state_20m.zip"
temp <- tempfile(fileext = ".zip")
download.file(url, temp, mode = "wb")
unzip(temp, exdir = "./data/Raw/Map")

states <- st_read("./data/Raw/Map/cb_2022_us_state_20m.shp")

layoff_data_city <- layoff_data_2015 %>%
    group_by(State) %>%
    summarize(total_laid_off_state = sum(`Number.of.Workers`))

city_data <- merge(states, layoff_data_city, by.x = "NAME", by.y = "State", all.x = TRUE)

ggplot() +
    geom_sf(data = city_data, aes(fill = total_laid_off_state), color = "white", size = 0.2) +
    scale_fill_viridis_c(labels = scales::number_format(scale = 1e-3, suffix = "K")) +
    theme_minimal() +
    labs(title = "Choropleth Map of Number.of.Workers Laid off in Each State") +
    coord_sf(xlim = c(-125, -66))
#
#
#

layoff_data_2015$Date <- as.Date(layoff_data_2015$Date, format = "%Y-%m-%d")
layoff_data_2015$effective_date_cleaned <- as.Date(layoff_data_2015$effective_date_cleaned, format = "%Y-%m-%d")

# Calculate the difference in days between the two dates
layoff_data_2015$days_difference <- as.numeric(difftime(layoff_data_2015$effective_date_cleaned, layoff_data_2015$Date, units = "days"))

# Plot the histogram
ggplot(layoff_data_2015, aes(x = days_difference)) +
    geom_histogram(binwidth = 1, fill = "skyblue", color = "black", alpha = 0.7) +
    labs(
        title = "Distribution of Days Between Date Received and Effective Date",
        x = "Days Difference",
        y = "Frequency"
    ) +
    theme_minimal()

#
#
#
#

remove_outliers_z <- function(data, column, threshold = 0.5) {
    z_scores <- scale(data[[column]])
    data[abs(z_scores) < threshold, , drop = FALSE]
}

# Remove outliers
data_no_outliers_z <- remove_outliers_z(layoff_data_2015, "days_difference")


ggplot(data_no_outliers_z, aes(x = days_difference)) +
    geom_histogram(binwidth = 1, fill = "skyblue", color = "black", alpha = 0.7) +
    labs(
        title = "Distribution of Days Between Date Received and Effective Date",
        x = "Days Difference",
        y = "Frequency"
    ) +
    theme_minimal()
#
#
#
# df_no_missing <- layoff_data[complete.cases(layoff_data$Date), ]
#
#
#
# df_no_missing[is.na(df_no_missing$`Date`),]
#
#
#
#

# json_data <- toJSON(df_no_missing, pretty = TRUE)
# writeLines(json_data, "data/Clean/layoff_json.json")
#
#
#
#| vscode: {languageId: r}
# Convert Date to the last date of the month
layoff_data <- layoff_data %>%
    mutate(
        last_day_of_month = floor_date(Date, "month") +
            days(days_in_month(Date) - 1)
    )

# Aggregate data at the monthly level
monthly_aggregated <- layoff_data %>%
    group_by(last_day_of_month) %>%
    summarize(num_of_workers_agg = sum(`Number.of.Workers`, na.rm = TRUE))
#
#
#
#| vscode: {languageId: r}
# filtered_layoff_data$`num_workers_scaled` <- filtered_layoff_data$`Number of Workers` / filtered_layoff_data$`Number of Workers`[1]*100
# snp_stock_indices_data$close_scaled <- snp_stock_indices_data$Close / snp_stock_indices_data$Close[1] * 100
# dji_stock_indices_data$close_scaled <- dji_stock_indices_data$Close / dji_stock_indices_data$Close[1] * 100
# nasdaq_stock_indices_data$close_scaled <- nasdaq_stock_indices_data$Close / nasdaq_stock_indices_data$Close[1] * 100
#
#
#
#| vscode: {languageId: r}
start_date <- as.POSIXct("2007-01-01")
end_date <- as.POSIXct("2019-12-31")

layoff_plot <- ggplot() +
    geom_line(
        data = monthly_aggregated |> filter(last_day_of_month >= start_date, last_day_of_month <= end_date),
        aes(x = last_day_of_month, y = num_of_workers_agg)
    ) +
    labs(
        y = "Layoffs per month",
        x = "",
        title = "Study of Layoff and Market Performace between 2007-2023",
        subtitle = "Layoff Trend",
    ) +
    theme_bw() +
    # theme(plot.title = element_text(face = "bold")) +
    scale_y_continuous(labels = scales::number_format(scale = 1))

stock_indices_plot <- ggplot() +
    geom_line(
        data = snp_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "S&P500")
    ) +
    geom_line(
        data = dji_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "Dow Jones Index")
    ) +
    geom_line(
        data = nasdaq_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "NASDAQ Composite")
    ) +
    labs(
        y = "Market Value",
        x = "Time",
        subtitle = "Major US Stock Indices",
    ) +
    theme_bw() +
    scale_y_continuous(labels = scales::number_format(scale = 1))

layoff_plot / stock_indices_plot
#
#
#
#| vscode: {languageId: r}
start_date <- as.POSIXct("2018-01-01")
end_date <- as.POSIXct("2023-12-31")


layoff_plot <- ggplot() +
    geom_line(
        data = monthly_aggregated |> filter(last_day_of_month >= start_date, last_day_of_month <= end_date),
        aes(x = last_day_of_month, y = num_of_workers_agg)
    ) +
    labs(
        y = "Layoffs per month",
        x = "",
        title = "Study of Layoff and Market Performace between 2018-2023",
        subtitle = "Layoff Trend",
    ) +
    theme_bw() +
    # theme(plot.title = element_text(face = "bold")) +
    scale_y_continuous(labels = scales::number_format(scale = 1))

stock_indices_plot <- ggplot() +
    geom_line(
        data = snp_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "S&P500")
    ) +
    geom_line(
        data = dji_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "Dow Jones Index")
    ) +
    geom_line(
        data = nasdaq_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "NASDAQ Composite")
    ) +
    labs(
        y = "Market Value",
        x = "Time",
        subtitle = "Major US Stock Indices",
    ) +
    theme_bw() +
    scale_y_continuous(labels = scales::number_format(scale = 1))

layoff_plot / stock_indices_plot
#
#
#
#| vscode: {languageId: r}
start_date <- as.POSIXct("2021-01-01")
end_date <- as.POSIXct("2023-12-31")


layoff_plot <- ggplot() +
    geom_line(
        data = monthly_aggregated |> filter(last_day_of_month >= start_date, last_day_of_month <= end_date),
        aes(x = last_day_of_month, y = num_of_workers_agg)
    ) +
    labs(
        y = "Layoffs per month",
        x = "",
        title = "Study of Layoff and Market Performace between 2021-2023",
        subtitle = "Layoff Trend",
    ) +
    theme_bw() +
    # theme(plot.title = element_text(face = "bold")) +
    scale_y_continuous(labels = scales::number_format(scale = 1))

stock_indices_plot <- ggplot() +
    geom_line(
        data = snp_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "S&P500")
    ) +
    geom_line(
        data = dji_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "Dow Jones Index")
    ) +
    geom_line(
        data = nasdaq_stock_indices_data |> filter(Date >= start_date, Date <= end_date),
        aes(x = Date, y = Close, color = "NASDAQ Composite")
    ) +
    labs(
        y = "Market Value",
        x = "Time",
        subtitle = "Major US Stock Indices",
    ) +
    theme_bw() +
    scale_y_continuous(labels = scales::number_format(scale = 1))

layoff_plot / stock_indices_plot
#
#
#
#| vscode: {languageId: r}
start_date <- as.POSIXct("2018-01-01")
end_date <- as.POSIXct("2023-12-31")
pk <- ggplot(
    data = monthly_aggregated |> filter(last_day_of_month >= start_date, last_day_of_month <= end_date),
    aes(x = last_day_of_month, y = num_of_workers_agg)
) +
    geom_line() +
    labs(
        x = "",
        y = "Layoffs per month",
        title = "Study of Layoff and Unemployment Trend between 2018-2023",
        subtitle = "Layoff Trend"
    ) +
    scale_y_continuous(labels = scales::number_format(scale = 1))

pd <- ggplot(
    data = unemployment_data |> filter(Date >= start_date, Date <= end_date),
    aes(x = Date, y = UNRATE)
) +
    geom_line() +
    labs(
        x = "Time",
        y = "Unemployment Rate",
        subtitle = "Unemployment Trend"
    ) +
    scale_y_continuous(labels = scales::number_format(scale = 1))
# pk
pk / pd
#
#
#
#| vscode: {languageId: r}
start_date <- as.POSIXct("2021-01-01")
end_date <- as.POSIXct("2023-12-31")
pk <- ggplot(
    data = monthly_aggregated |> filter(last_day_of_month >= start_date, last_day_of_month <= end_date),
    aes(x = last_day_of_month, y = num_of_workers_agg)
) +
    geom_line() +
    labs(
        x = "",
        y = "Layoffs per month",
        title = "Study of Layoff and Unemployment Trend between 2021-2023",
        subtitle = "Layoff Trend"
    ) +
    scale_y_continuous(labels = scales::number_format(scale = 1))

pd <- ggplot(
    data = unemployment_data |> filter(Date >= start_date, Date <= end_date),
    aes(x = Date, y = UNRATE)
) +
    geom_line() +
    labs(
        x = "Time",
        y = "Unemployment Rate",
        subtitle = "Unemployment Trend"
    ) +
    scale_y_continuous(labels = scales::number_format(scale = 1))
# pk
pk / pd
#
#
#
#| vscode: {languageId: r}
layoff_data$year <- as.numeric(format(layoff_data$Date, "%Y"))

layoff_reason_summary <- layoff_data |>
    drop_na(layoff_type_cleaned) |>
    group_by(year, layoff_type_cleaned) |>
    summarize(total_layoffs = sum(`Number.of.Workers`, na.rm = TRUE))
#
#
#
#| vscode: {languageId: r}
options(repr.plot.width = 20, repr.plot.height = 12)
start_date <- 2018
end_date <- 2023

# Create a Cleveland dot plot
ggplot(
    layoff_reason_summary |> filter(year >= start_date, year <= end_date),
    aes(y = reorder(layoff_type_cleaned, total_layoffs), x = total_layoffs)
) +
    geom_point() +
    facet_wrap(~year, nrow = 1) +
    labs(
        y = "Layoff Reason",
        x = "# of Workers Laid off",
        title = "Study of Layoff reasons over the recent years 2018 - 2023"
    ) +
    theme_bw() +
    scale_x_continuous(labels = scales::number_format(scale = 1))
#
#
#
#
#
